### PR TITLE
closes #46 lister can edit profile fix

### LINKED ISSUE #45: Contractor Can Edit Their Profile
As a logged in contractor,
When I visit /dashboard,
And I click on Edit Profile,
Then I see an edit form mirroring the sign up form,
And when I update any of the fields,
And when I click on "Update Information",
I am redirected the dashboard and I see the updated information.

### LINKED ISSUE #46: Lister Can Edit Their Profile
As a logged in lister,
When I visit /dashboard,
And I click on Edit Profile,
Then I see an edit form mirroring the sign up form,
And I do not see a "Role" field,
And when I update any of the fields,
And when I click on "Update Information",
I am redirected the dashboard and I see the updated information.

### PR DESCRIPTION
**Pull request by jwperry**
Closes #46 
Closes #45 
- Feature testing for user profile edit
- Fixed minor error with .admin? call in users_controller.rb
- Removed extraneous file field, labeled persisting file field
- Included contractor role edit in test

### CODE REVIEW

File: app/controllers/user/users_controller.rb [hunk 1]
```diff
@@ -31,7 +31,7 @@ def edit
 
   def update
     if @user.update_attributes(user_params)
-      if current_user.admin?
+      if current_user.platform_admin?
```
Comment (ToniRib) [inline app/controllers/user/users_controller.rb:34]: Good catch! :+1:

File: test/integration/lister_can_edit_profile_test.rb [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+    refute page.has_content?(original_lister.last_name)
+    refute page.has_content?(original_lister.email_address)
+    refute page.has_content?(original_lister.street_address)
+    refute page.has_content?(original_lister.city)
+    refute page.has_content?(original_lister.state)
+    refute page.has_content?(original_lister.zipcode)
+    refute page.has_content?(original_lister.bio)
+  end
+
+  test "listers editing profile may not change role" do
```
Comment (ToniRib) [inline test/integration/lister_can_edit_profile_test.rb]: I feel like it would make more sense to split this up into two tests:
  1) Contractor can edit their role to be a lister - verify within this test that they actually do change their role
  2) Lister cannot edit their role (go to the edit page and assert their only option is lister)

@danjwinter any thoughts?

Comment (danjwinter) [inline test/integration/lister_can_edit_profile_test.rb]: Yeah, it makes sense to split up the logic for the different users. It will also help down the road when we look at file names at a glance to see exactly what they are testing.

**Comment by jwperry** [comment]
I agree. Will split this out. We probably don't need a separate test file for contractor profile editing as it's the same functionality as the lister except for the dropdown. Will split test, and close #45 and #46 with this branch.

File: test/integration/lister_can_edit_profile_test.rb (hunk 2 above)
Comment (jwperry) [inline test/integration/lister_can_edit_profile_test.rb]: I agree. Will split this out. We probably don't need a separate test file for contractor profile editing as it's the same functionality as the lister except for the dropdown. Will split test, and close #45 and #46 with this branch.

File: test/integration/user_can_edit_profile_test.rb [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+    assert edit_user_path(contractor), current_path
+
+    select "lister", from: "Role"
+
+    click_on "Update User"
+    contractor.reload
+    assert_equal dashboard_path, current_path
+    assert_equal "lister", contractor.role
+  end
+
```
Comment (ToniRib) [inline test/integration/user_can_edit_profile_test.rb:113]: Cool, I like these tests split up a lot better!

**Comment by jwperry** [comment]
Can't rebase last Hound styling commit, not showing with rebase command, letting it go to avoid errors.

**Comment by ToniRib** [comment]
Looks good to me, I'm going to merge this in. I saw what happened with the rebase and I agree, let's not try to rebase it this time.
